// TXT export utility for Study Planner tasks

import type { StudyTask } from '@/hooks/useQueries';
import type { GuestStudyTask } from './studyPlannerGuestStorage';
import { formatTaskDateTime } from './studyPlannerTaskDateTime';

interface ExportOptions {
  tasks: Array<StudyTask | GuestStudyTask>;
  viewType: 'daily' | 'weekly';
}

/**
 * Export tasks to a clean, Notepad-friendly TXT file
 */
export function exportTasksToTxt({ tasks, viewType }: ExportOptions): void {
  const lines: string[] = [];
  const separator = '------------------------------------';

  // Header
  lines.push('STUDY PLANNER');
  lines.push(`View: ${viewType === 'daily' ? 'Daily' : 'Weekly'}`);
  lines.push(`Generated: ${new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  })}`);
  lines.push(separator);

  // Summary counts
  const totalCount = tasks.length;
  const completedCount = tasks.filter((t) => t.isCompleted).length;
  const pendingCount = totalCount - completedCount;

  lines.push(`Total Tasks: ${totalCount} | Completed: ${completedCount} | Pending: ${pendingCount}`);
  lines.push(separator);
  lines.push('');

  // Task list
  if (tasks.length === 0) {
    lines.push('No tasks to display.');
  } else {
    tasks.forEach((task, index) => {
      // Status
      const status = task.isCompleted ? '✓ Completed' : '○ Pending';
      lines.push(`${index + 1}. ${status}`);

      // Subject
      lines.push(`   Subject: ${task.subject}`);

      // Topic
      lines.push(`   Topic: ${task.topic}`);

      // Duration
      lines.push(`   Duration: ${task.duration}`);

      // Date & Time (only if present)
      const dateTimeDisplay = formatTaskDateTime(task.date, task.time);
      if (dateTimeDisplay) {
        lines.push(`   Date & Time: ${dateTimeDisplay}`);
      }

      // Priority (only if present)
      if (task.priority) {
        lines.push(`   Priority: ${task.priority}`);
      }

      lines.push('');
    });
  }

  // Footer
  lines.push(separator);
  lines.push('Generated by Study Planner App');

  // Create and download file
  const content = lines.join('\n');
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `study-plan-${viewType}-${Date.now()}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
