// PDF export utility for Study Planner tasks
// Uses browser-native approach to generate PDF-like formatted text

import type { StudyTask } from '@/hooks/useQueries';
import type { GuestStudyTask } from './studyPlannerGuestStorage';
import { formatTaskDateTime } from './studyPlannerTaskDateTime';

interface ExportOptions {
  tasks: Array<StudyTask | GuestStudyTask>;
  viewType: 'daily' | 'weekly';
}

/**
 * Export tasks to a well-formatted text file with PDF-like structure
 * This creates a clean, printable document that can be saved as PDF by the user
 */
export async function exportTasksToPdf({ tasks, viewType }: ExportOptions): Promise<void> {
  // Create a formatted HTML document that can be printed as PDF
  const htmlContent = generatePdfHtml(tasks, viewType);
  
  // Open in new window for printing
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    throw new Error('Could not open print window. Please allow popups.');
  }
  
  printWindow.document.write(htmlContent);
  printWindow.document.close();
  
  // Wait for content to load, then trigger print dialog
  printWindow.onload = () => {
    printWindow.focus();
    printWindow.print();
  };
}

function generatePdfHtml(tasks: Array<StudyTask | GuestStudyTask>, viewType: 'daily' | 'weekly'): string {
  const totalCount = tasks.length;
  const completedCount = tasks.filter((t) => t.isCompleted).length;
  const pendingCount = totalCount - completedCount;
  
  const generatedDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  let tasksHtml = '';
  
  if (tasks.length === 0) {
    tasksHtml = '<p style="text-align: center; color: #666; margin: 40px 0;">No tasks to display.</p>';
  } else {
    tasks.forEach((task, index) => {
      const status = task.isCompleted ? '✔' : '○';
      const statusText = task.isCompleted ? 'Completed' : 'Pending';
      const dateTimeDisplay = formatTaskDateTime(task.date, task.time);
      
      tasksHtml += `
        <div style="margin-bottom: 24px; padding: 16px; border: 1px solid #e0e0e0; border-radius: 8px; page-break-inside: avoid;">
          <div style="font-weight: bold; font-size: 14px; margin-bottom: 12px;">
            ${index + 1}. ${status} ${statusText}
          </div>
          <div style="margin-left: 20px; line-height: 1.8;">
            <div><strong>Subject:</strong> ${escapeHtml(task.subject)}</div>
            <div><strong>Topic:</strong> ${escapeHtml(task.topic)}</div>
            <div><strong>Duration:</strong> ${escapeHtml(task.duration)}</div>
            ${dateTimeDisplay ? `<div><strong>Date & Time:</strong> ${escapeHtml(dateTimeDisplay)}</div>` : ''}
            ${task.priority ? `<div><strong>Priority:</strong> ${escapeHtml(task.priority)}</div>` : ''}
          </div>
        </div>
      `;
    });
  }

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>Study Planner - ${viewType === 'daily' ? 'Daily' : 'Weekly'}</title>
      <style>
        @media print {
          body { margin: 0; }
          @page { margin: 1cm; }
        }
        body {
          font-family: Arial, sans-serif;
          max-width: 800px;
          margin: 0 auto;
          padding: 40px 20px;
          color: #333;
        }
        h1 {
          text-align: center;
          font-size: 28px;
          margin-bottom: 10px;
          color: #000;
        }
        .subtitle {
          text-align: center;
          font-size: 14px;
          color: #666;
          margin-bottom: 8px;
        }
        .summary {
          text-align: center;
          font-weight: bold;
          font-size: 13px;
          margin: 30px 0;
          padding: 12px;
          background: #f5f5f5;
          border-radius: 6px;
        }
        .separator {
          border-top: 2px solid #ddd;
          margin: 30px 0;
        }
        .footer {
          text-align: center;
          font-style: italic;
          font-size: 11px;
          color: #999;
          margin-top: 40px;
          padding-top: 20px;
          border-top: 1px solid #e0e0e0;
        }
      </style>
    </head>
    <body>
      <h1>STUDY PLANNER</h1>
      <div class="subtitle">View: ${viewType === 'daily' ? 'Daily' : 'Weekly'}</div>
      <div class="subtitle">Generated: ${generatedDate}</div>
      
      <div class="summary">
        Total Tasks: ${totalCount} &nbsp;|&nbsp; Completed: ${completedCount} &nbsp;|&nbsp; Pending: ${pendingCount}
      </div>
      
      <div class="separator"></div>
      
      ${tasksHtml}
      
      <div class="footer">
        Generated by Study Planner App
      </div>
    </body>
    </html>
  `;
}

function escapeHtml(text: string): string {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}
