/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const StudyPlannerView = IDL.Variant({
  'daily' : IDL.Null,
  'weekly' : IDL.Null,
});
export const Time = IDL.Int;
export const OptionalTime = IDL.Record({
  'hour' : IDL.Nat,
  'minute' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AssignmentId = IDL.Nat;
export const Assignment = IDL.Record({
  'id' : AssignmentId,
  'topic' : IDL.Text,
  'content' : ExternalBlob,
  'level' : IDL.Text,
  'language' : IDL.Text,
  'length' : IDL.Text,
  'timestamp' : Time,
});
export const AnnouncementId = IDL.Nat;
export const Announcement = IDL.Record({
  'id' : AnnouncementId,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const StudyTaskPublic = IDL.Record({
  'id' : IDL.Nat,
  'created' : Time,
  'topic' : IDL.Text,
  'duration' : IDL.Text,
  'subject' : IDL.Text,
  'isCompleted' : IDL.Bool,
  'date' : IDL.Opt(Time),
  'subjectColor' : IDL.Opt(IDL.Text),
  'time' : IDL.Opt(OptionalTime),
  'viewType' : IDL.Opt(StudyPlannerView),
  'priority' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTask' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(StudyPlannerView),
        IDL.Opt(IDL.Text),
        IDL.Opt(Time),
        IDL.Opt(OptionalTime),
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAnnouncement' : IDL.Func([IDL.Text], [], []),
  'createAssignment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
      [Assignment],
      [],
    ),
  'deleteAnnouncement' : IDL.Func([AnnouncementId], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'dragDropReorder' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
  'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
  'getAssignment' : IDL.Func([AssignmentId], [IDL.Opt(Assignment)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFilteredTasks' : IDL.Func(
      [IDL.Opt(StudyPlannerView)],
      [IDL.Vec(StudyTaskPublic)],
      ['query'],
    ),
  'getTaskCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getTasks' : IDL.Func([], [IDL.Vec(StudyTaskPublic)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveConversationEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setView' : IDL.Func([StudyPlannerView], [], []),
  'submitFeatureRequest' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'toggleTaskCompletion' : IDL.Func([IDL.Nat], [], []),
  'undoLastTask' : IDL.Func([], [], []),
  'updateTask' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(StudyPlannerView),
        IDL.Opt(IDL.Text),
        IDL.Opt(Time),
        IDL.Opt(OptionalTime),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const StudyPlannerView = IDL.Variant({
    'daily' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const Time = IDL.Int;
  const OptionalTime = IDL.Record({ 'hour' : IDL.Nat, 'minute' : IDL.Nat });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AssignmentId = IDL.Nat;
  const Assignment = IDL.Record({
    'id' : AssignmentId,
    'topic' : IDL.Text,
    'content' : ExternalBlob,
    'level' : IDL.Text,
    'language' : IDL.Text,
    'length' : IDL.Text,
    'timestamp' : Time,
  });
  const AnnouncementId = IDL.Nat;
  const Announcement = IDL.Record({
    'id' : AnnouncementId,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const StudyTaskPublic = IDL.Record({
    'id' : IDL.Nat,
    'created' : Time,
    'topic' : IDL.Text,
    'duration' : IDL.Text,
    'subject' : IDL.Text,
    'isCompleted' : IDL.Bool,
    'date' : IDL.Opt(Time),
    'subjectColor' : IDL.Opt(IDL.Text),
    'time' : IDL.Opt(OptionalTime),
    'viewType' : IDL.Opt(StudyPlannerView),
    'priority' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTask' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(StudyPlannerView),
          IDL.Opt(IDL.Text),
          IDL.Opt(Time),
          IDL.Opt(OptionalTime),
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAnnouncement' : IDL.Func([IDL.Text], [], []),
    'createAssignment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
        [Assignment],
        [],
      ),
    'deleteAnnouncement' : IDL.Func([AnnouncementId], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'dragDropReorder' : IDL.Func([IDL.Vec(IDL.Nat)], [], []),
    'getAllAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllAssignments' : IDL.Func([], [IDL.Vec(Assignment)], ['query']),
    'getAssignment' : IDL.Func(
        [AssignmentId],
        [IDL.Opt(Assignment)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFilteredTasks' : IDL.Func(
        [IDL.Opt(StudyPlannerView)],
        [IDL.Vec(StudyTaskPublic)],
        ['query'],
      ),
    'getTaskCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getTasks' : IDL.Func([], [IDL.Vec(StudyTaskPublic)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveConversationEntry' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setView' : IDL.Func([StudyPlannerView], [], []),
    'submitFeatureRequest' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'toggleTaskCompletion' : IDL.Func([IDL.Nat], [], []),
    'undoLastTask' : IDL.Func([], [], []),
    'updateTask' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(StudyPlannerView),
          IDL.Opt(IDL.Text),
          IDL.Opt(Time),
          IDL.Opt(OptionalTime),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };