/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : AnnouncementId,
  'message' : string,
  'timestamp' : Time,
}
export type AnnouncementId = bigint;
export interface Assignment {
  'id' : AssignmentId,
  'topic' : string,
  'content' : ExternalBlob,
  'level' : string,
  'language' : string,
  'length' : string,
  'timestamp' : Time,
}
export type AssignmentId = bigint;
export type ExternalBlob = Uint8Array;
export interface OptionalTime { 'hour' : bigint, 'minute' : bigint }
export type StudyPlannerView = { 'daily' : null } |
  { 'weekly' : null };
export interface StudyTaskPublic {
  'id' : bigint,
  'created' : Time,
  'topic' : string,
  'duration' : string,
  'subject' : string,
  'isCompleted' : boolean,
  'date' : [] | [Time],
  'subjectColor' : [] | [string],
  'time' : [] | [OptionalTime],
  'viewType' : [] | [StudyPlannerView],
  'priority' : [] | [string],
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTask' : ActorMethod<
    [
      string,
      string,
      string,
      [] | [string],
      [] | [StudyPlannerView],
      [] | [string],
      [] | [Time],
      [] | [OptionalTime],
    ],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAnnouncement' : ActorMethod<[string], undefined>,
  'createAssignment' : ActorMethod<
    [string, string, string, string, ExternalBlob],
    Assignment
  >,
  'deleteAnnouncement' : ActorMethod<[AnnouncementId], undefined>,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'dragDropReorder' : ActorMethod<[Array<bigint>], undefined>,
  'getAllAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllAssignments' : ActorMethod<[], Array<Assignment>>,
  'getAssignment' : ActorMethod<[AssignmentId], [] | [Assignment]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFilteredTasks' : ActorMethod<
    [[] | [StudyPlannerView]],
    Array<StudyTaskPublic>
  >,
  'getTaskCount' : ActorMethod<[], bigint>,
  'getTasks' : ActorMethod<[], Array<StudyTaskPublic>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveConversationEntry' : ActorMethod<[string, string], undefined>,
  'setView' : ActorMethod<[StudyPlannerView], undefined>,
  'submitFeatureRequest' : ActorMethod<[string, [] | [string]], undefined>,
  'toggleTaskCompletion' : ActorMethod<[bigint], undefined>,
  'undoLastTask' : ActorMethod<[], undefined>,
  'updateTask' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      [] | [string],
      [] | [StudyPlannerView],
      [] | [string],
      [] | [Time],
      [] | [OptionalTime],
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];